//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_Server_Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class ColorTheme : global::System.Configuration.ApplicationSettingsBase {
        
        private static ColorTheme defaultInstance = ((ColorTheme)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ColorTheme())));
        
        public static ColorTheme Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Text {
            get {
                return ((global::System.Drawing.Color)(this["Text"]));
            }
            set {
                this["Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Icon {
            get {
                return ((global::System.Drawing.Color)(this["Icon"]));
            }
            set {
                this["Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color MouseDown {
            get {
                return ((global::System.Drawing.Color)(this["MouseDown"]));
            }
            set {
                this["MouseDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 77")]
        public global::System.Drawing.Color MouseHover {
            get {
                return ((global::System.Drawing.Color)(this["MouseHover"]));
            }
            set {
                this["MouseHover"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38, 38, 38")]
        public global::System.Drawing.Color FormBG {
            get {
                return ((global::System.Drawing.Color)(this["FormBG"]));
            }
            set {
                this["FormBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50, 50")]
        public global::System.Drawing.Color FormBGPopup {
            get {
                return ((global::System.Drawing.Color)(this["FormBGPopup"]));
            }
            set {
                this["FormBGPopup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12, 190, 228")]
        public global::System.Drawing.Color HomeBTN {
            get {
                return ((global::System.Drawing.Color)(this["HomeBTN"]));
            }
            set {
                this["HomeBTN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("243, 0, 0")]
        public global::System.Drawing.Color ExitBTN {
            get {
                return ((global::System.Drawing.Color)(this["ExitBTN"]));
            }
            set {
                this["ExitBTN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("77, 224, 16")]
        public global::System.Drawing.Color Confirm {
            get {
                return ((global::System.Drawing.Color)(this["Confirm"]));
            }
            set {
                this["Confirm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("243, 0, 0")]
        public global::System.Drawing.Color Cancel {
            get {
                return ((global::System.Drawing.Color)(this["Cancel"]));
            }
            set {
                this["Cancel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35, 0, 45")]
        public global::System.Drawing.Color MenuActive {
            get {
                return ((global::System.Drawing.Color)(this["MenuActive"]));
            }
            set {
                this["MenuActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TextBoxBG {
            get {
                return ((global::System.Drawing.Color)(this["TextBoxBG"]));
            }
            set {
                this["TextBoxBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TextBoxText {
            get {
                return ((global::System.Drawing.Color)(this["TextBoxText"]));
            }
            set {
                this["TextBoxText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::System.Drawing.Color Loading {
            get {
                return ((global::System.Drawing.Color)(this["Loading"]));
            }
            set {
                this["Loading"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65, 65, 65")]
        public global::System.Drawing.Color FormBGPopupTopBar {
            get {
                return ((global::System.Drawing.Color)(this["FormBGPopupTopBar"]));
            }
            set {
                this["FormBGPopupTopBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ExitBTNConfirm {
            get {
                return ((global::System.Drawing.Color)(this["ExitBTNConfirm"]));
            }
            set {
                this["ExitBTNConfirm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ExitBTNCancel {
            get {
                return ((global::System.Drawing.Color)(this["ExitBTNCancel"]));
            }
            set {
                this["ExitBTNCancel"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlDark")]
        public global::System.Drawing.Color IconSteam {
            get {
                return ((global::System.Drawing.Color)(this["IconSteam"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color IconValheim {
            get {
                return ((global::System.Drawing.Color)(this["IconValheim"]));
            }
            set {
                this["IconValheim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DimGray")]
        public global::System.Drawing.Color MenuSelected {
            get {
                return ((global::System.Drawing.Color)(this["MenuSelected"]));
            }
            set {
                this["MenuSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38, 38, 38")]
        public global::System.Drawing.Color FormBGChild {
            get {
                return ((global::System.Drawing.Color)(this["FormBGChild"]));
            }
            set {
                this["FormBGChild"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38, 38, 38")]
        public global::System.Drawing.Color ButtonBG {
            get {
                return ((global::System.Drawing.Color)(this["ButtonBG"]));
            }
            set {
                this["ButtonBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 0, 0")]
        public global::System.Drawing.Color IconDisabled {
            get {
                return ((global::System.Drawing.Color)(this["IconDisabled"]));
            }
            set {
                this["IconDisabled"] = value;
            }
        }
    }
}
